/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package misty.fw.api.module;

import org.junit.Test;
import org.misty.fw.api.module.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
